# Development staging configuration. Extends base configuration.
version: "3.7"
services:
  connex-fetcher:
    build:
      target: production
    environment:
      - NODE_ENV=production
      - CHAIN_ID=100010
      - DISCORD_WEBHOOK_URL=DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1199940499834945626/H_Rp0ghYdbzcMH4HFs7KHbTR1ih6iOEVxO2lg9Fbj2uRVOBNVWZWWEBhbVMfP77eTktU
    command: node dist/index.js
