# Development staging configuration. Extends base configuration.
version: "3.7"
services:
  connex-fetcher:
    build:
      target: production
    environment:
      - NODE_ENV=production
      - CHAIN_ID=100010
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    command: node dist/index.js
