# Shared configuration across environments.
version: "3.7"
# List of containers
services:
  # Container name
  connex-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: vearnfi/events-fetcher
    environment:
      - PORT=5000
    restart: unless-stopped
