# Shared configuration across environments.
version: "3"
services:
  # ^ List of containers
  connex-fetcher:
    # ^ Container name
    build: .
      # ^ Build the container based on the provided image (path to Dockerfile)
    environment:
      - PORT=5000
