# Development environment configuration. Extends base configuration.
version: "3.7"
services:
  connex-fetcher:
    build:
      # ^ Build the container based on the provided image (path to Dockerfile)
      target: base
    volumes:
      - ./src:/app/src:ro
      # - /app/node_modules
      # ^ Only required in dev mode to sync code changes
    environment:
      - NODE_ENV=development
      - CHAIN_ID=100011
    network_mode: "host"
    command: npm run dev
