# Development environment configuration. Extends base configuration.
version: "3.7"
services:
  connex-fetcher:
    build:
      target: builder
    volumes:
      - ./src:/app/src:ro
      # - /app/node_modules
      # ^ Only required in dev mode to sync code changes
    environment:
      - NODE_ENV=development
      - CHAIN_ID=100011
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1199940499834945626/H_Rp0ghYdbzcMH4HFs7KHbTR1ih6iOEVxO2lg9Fbj2uRVOBNVWZWWEBhbVMfP77eTktU
    network_mode: "host"
    command: npm run dev
