# Shared configuration across environments.
version: "3.7"
services:
  # ^ List of containers
  connex-fetcher:
    # ^ Container name
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
